name: Docker build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Test Docker image
        run: docker build -t teste-mini-explicador .